language: rust
rust:
  - stable
  - beta
  - nightly
sudo: false
script:
  - cargo test
  - cargo test --no-default-features
  - cargo test --no-default-features --features 'libunwind'
  - cargo test --no-default-features --features 'libunwind dladdr'
  - cargo test --no-default-features --features 'libunwind libbacktrace'
  - cargo test --no-default-features --features 'unix-backtrace'
  - cargo test --no-default-features --features 'unix-backtrace dladdr'
  - cargo test --no-default-features --features 'unix-backtrace libbacktrace'
  - rustdoc --test README.md -L target/debug/deps -L target/debug
notifications:
  email:
    on_success: never
