[package]
name = "backtrace"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[dependencies]
libc = "0.1"
backtrace-sys = { path = "backtrace-sys", version = "0.1", optional = true }

[features]
libunwind = []
unix-backtrace = []
libbacktrace = ["backtrace-sys"]
dladdr = []
